### ISSUE TITLE
Barcode cell type annotation labels

### ISSUE THREAD

**Issue by RegnerM2015** [p4rkerw/Muto_Wilson_NComm_2020#2]
Hi @p4rkerw @ymuto802 

Would you be able to point me in the right direction of cell type annotations for the barcodes?

I am looking on GEO here:https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE151302 

It looks like there are just feature barcode matrices. If you could provide a table or file showing the cell type annotations for every barcode in each sample, that would be greatly appreciated!

**Comment by p4rkerw** [comment]
Thanks for the comment. I dropped a csv file in the snRNA_prep and snATAC_prep directories with their respective barcode-sample-celltype annotations. There's additional metadata on the cellxgene website but this will make them easy to find. - Parker
