### ISSUE TITLE
Analysis of uploaded data was troublesome in current dataset. 

### ISSUE THREAD

**Issue by smilesw** [p4rkerw/Muto_Wilson_NComm_2020#4]
Dear Sir 
I read your recently published article with a special interest. To analyze your data,  I downloaded uploaded raw and processed data from GEO and European Nucleotide Archive (ENA). But I cannot further process the data by following your analysis code because of 

1) when performing cellranger-atac count, the following message showed up.

-> there was no I2 read FASTQ and we were unable to read a 16-base barcode from the FASTQ header  

2) when analyzing processed data,  I can make seurat object of each sample, but I cannot integrate each sample into merged object appropriately due to a lack of necessary files such as peaks.bed and singlecell.csv.

Would you share the necessary files if you don't mind? Thanks in advance. I hope that it does not bother you much.

**Comment by p4rkerw** [comment]
Hello,
We're in the process of transferring data to the human cell atlas website through CZI and they should have all these files available in the near future. I'll put the link in the repository welcome page when it goes live. If those files aren't part of the HCA dataset I'll look into uploading them to GEO. 
Parker

**Comment by smilesw** [comment]
Hello
Actually, I found that original data in NCBI's google cloud or amazon cloud showed that fastq format of index files was uploaded as original data. So I tried to use those materials. 
Thank you for providing the information.

**Comment by p4rkerw** [comment]
Ok sounds great! The data can also be found on the HCA portal located here: https://data.humancellatlas.org/explore/projects/2af52a13-65cb-4973-b513-39be38f2df3f/project-matrices
