### ISSUE TITLE
About Figure 3a

### ISSUE THREAD

**Issue by anlin00007** [p4rkerw/Muto_Wilson_NComm_2020#5]
Hello,

I am trying to replicate the Figure 3a, heatmap of ChromVAR motifs. However, I couldn't find the file 'cellranger_atac_prep/chromVar.atacAggr_sub97_control.rds'. Could you point me the location of that file?

Thanks

**Comment by p4rkerw** [comment]
Hello Anlin00007,
This file is not publicly-available but you can generate it using the processed datasets in GEO and code in the repository

**Comment by anlin00007** [comment]
In this case, may I have a clear version of the figure 3a with the row names available? I am interested in what TFs are included in each cluster.
