### ISSUE TITLE
Singlecell.csv file unavailable

### ISSUE THREAD

**Issue by Sanat-Mishra** [p4rkerw/Muto_Wilson_NComm_2020#6]
Hi,

Can the required files needed to perform the Seurat and Signac single-cell analysis be made available?

Thanks!

**Comment by p4rkerw** [comment]
Yes I can get you the files you need. Send me an email at my UPenn address and we can set up a link to transfer.

**Comment by Sanat-Mishra** [comment]
Dear Dr. Wilson,

I emailed you at your UPenn email via my university mail id.

Thanks,
Sanat

On Jun 10, 2023, at 7:25 AM, Parker C. Wilson, MD, PhD ***@***.***> wrote:

﻿

Yes I can get you the files you need. Send me an email at my UPenn address and we can set up a link to transfer.
